# Generated by Django 4.2.1 on 2023-06-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the resident')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('focus', 'Focus'), ('team', 'Team'), ('conference', 'Conference')], max_length=50, verbose_name='Type of the room')),
                ('capacity', models.IntegerField(choices=[(15, 15), (5, 5), (1, 1)], verbose_name='Capacity of the room')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('start', models.TimeField(verbose_name='Start time')),
                ('end', models.TimeField(verbose_name='End time')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is this time available')),
                ('name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.resident', verbose_name='Name of the resident')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='api.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Available time',
                'verbose_name_plural': 'Available times',
            },
        ),
    ]
