# Generated by Django 4.2.1 on 2023-06-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_availability_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='name',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('start', models.TimeField(verbose_name='Start time')),
                ('end', models.TimeField(verbose_name='End time')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.resident', verbose_name='Resident')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.room', verbose_name='Room')),
            ],
        ),
    ]
